version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URL
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t poker-planning ./server
      - docker tag poker-planning:latest $ECR_REPOSITORY_URL/poker-planning:latest
      - echo Building the client...
      - cd client && npm install && npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REPOSITORY_URL/poker-planning:latest
      - echo Writing image definitions file...
      - cd ..  
      - printf '[{"name":"poker-planning","imageUri":"%s/poker-planning:latest"}]' $ECR_REPOSITORY_URL > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - client/dist/**